
export interface BilanChocaSisal {
    bilan_nb_pop: number,
    lutte_encours_percent: number,
    lutte_end: number,
    lutte_end_partial: number,
    lutte_end_percent: number,
    lutte_endpartial_percent: number,
    lutte_nb: number,
    lutte_nb_arrache: number,
    lutte_nb_coupe: number,
    lutte_nb_encours: number,
    lutte_nb_h: number,
    lutte_nb_ident: number,
    lutte_nb_sans: number,
    lutte_pds: number,
    lutte_sans_percent: number,
    lutte_suivi: number,
    lutte_surf_traite: number,
    lutte_surf_tt_percent: number,
    nb_collecte: number,
    pop_taxon_id: number,
    suivi_mois_max: number,
    suivi_mois_min: number,
    suivi_nb: number,
    suivi_nb_arrache: number,
    suivi_nb_h: number,
    suivi_nb_ident: number,
    suivi_pds_bulb: number,
    surf_init: number,
    taxon_lib: string
}

export interface BilanFataque {
    bilan_nb_pop: number,
    lutte_encours_percent: number,
    lutte_end: number,
    lutte_end_partial: number,
    lutte_end_percent: number,
    lutte_endpartial_percent: number,
    lutte_nb: number,
    lutte_nb_arrache: number,
    lutte_nb_coupe: number,
    lutte_nb_encours: number,
    lutte_nb_h: number,
    lutte_nb_ident: number,
    lutte_nb_sans: number,
    lutte_pds: number,
    lutte_sans_percent: number,
    lutte_suivi: number,
    lutte_surf_traite: number,
    lutte_surf_tt_percent: number,
    nb_collecte: number,
    pop_taxon_id: number,
    suivi_mois_max: number,
    suivi_mois_min: number,
    suivi_nb: number,
    suivi_nb_arrache: number,
    suivi_nb_h: number,
    suivi_nb_ident: number,
    suivi_pds_bulb: number,
    surf_init: number,
    taxon_lib: string,
    lutte_suivi_one: number
}